application:
  security:
    token:
      secretKey: t8$F&M?ytmp%bsdz$\JCB+@C2
      expiration: 3600000 # 1 hour

server:
  port: ${SERVER_PORT:8090}

spring:
  datasource:
    url: jdbc:h2:mem:app_db
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath:/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
