application:
  jwtSecret: JWT_SECRET
  jwtValidity: 86400000

server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    initialization-mode: always
    data: classpath:/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true
    properties:
      hibernate:
        format_sql: true