application:
  security:
    token:
      secret-key: t8$F&M?ytmp%bsdz$\JCB+@C2
      expiration: 3600000 # 1 hour

server:
  port: ${SERVER_PORT:8090}
  servlet.context-path: /api

spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/app_db
    username: app_user
    password: app_password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/changelog-prod.xml

